### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by Kwenziwa** [io-digital/PeachPayment#10]
Hi there 

Just a quick question, does this package include 3D Secure?

**Comment by g0dReVeN** [comment]
Hi, 

Not sure I fully understand your question. The responsibility of the implementation of 3D Secure falls on the issuer of bank card used for payments. I believe the web UI aspect of 3D Secure is provided by the combination of payment networks & the banks via the JavaScript widget provided by Peach Payments which is required to accept card payments.

For more info, please refer to:

- https://peachpayments.zendesk.com/hc/en-us/articles/360026908771-What-is-3D-Secure-
- https://peachpayments.zendesk.com/hc/en-us/articles/203404766-3DSecure-and-CopyandPay
